name: Sussex Air Imaging
favicon: null
layout_spectrum: 0.7277326774783432
typography_spectrum: 0.9336023868527263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.761501443805173
  lightness: 0.9646726534701884
  saturation: 0.45627883612178266
  rhythmicContrast: 0.6598176709376276
purpose: []
