name: Sussex Air Imaging
favicon: null
layout_spectrum: 0.7862
typography_spectrum: 0.39315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#393433'
    - '#9b9b9b'
    - '#2089c7'
    - '#c0c0c0'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.6598176709376276
purpose: []
