name: Sussex Air Imaging
favicon: null
layout_spectrum: 0.10181
typography_spectrum: 0.39315
title: Drone/UAV filming and photography for East and West Sussex
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#afbfd4'
    - '#8f99b5'
    - '#677b9d'
    - '#4e596c'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
